apiVersion: apps/v1
kind: Deployment
metadata:
  name: attu
  namespace: milvus-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attu
  template:
    metadata:
      labels:
        app: attu
    spec:
      containers:
        - name: attu
          image: zilliz/attu:latest
          ports:
            - containerPort: 3000
          env:
            - name: MILVUS_URL
              value: "milvus-proxy:19530"
---
apiVersion: v1
kind: Service
metadata:
  name: attu
  namespace: milvus-operator
spec:
  type: NodePort
  selector:
    app: attu
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30030
