apiVersion: v1
kind: Service
metadata:
  name: milvus
  namespace: milvus-operator
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: milvus
  ports:
    - name: grpc
      port: 19530
      targetPort: 19530
      nodePort: 32090
      protocol: TCP
    - name: http
      port: 9091
      targetPort: 9091
      nodePort: 32691
      protocol: TCP
