apiVersion: v1
kind: Service
metadata:
  name: milvus-distributed-minio
  namespace: milvus-operator
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: 30900
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30901
